vich_uploader:
    db_driver: orm

    mappings:
       main_image:
           uri_prefix: /images/tricks
           upload_destination: '%kernel.project_dir%/public/images/tricks'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
           
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
